import { ICountry } from './models';

export const Countries: ICountry = {
  DZ: { name: 'Algeria' },
  AR: { name: 'Argentina' },
  AU: { name: 'Australia' },
  BE: { name: 'Belgium' },
  BR: { name: 'Brazil' },
  BG: { name: 'Bulgaria' },
  KH: { name: 'Cambodia' },
  CM: { name: 'Cameroon' },
  CA: { name: 'Canada' },
  CN: { name: 'China' },
  CO: { name: 'Colombia' },
  CU: { name: 'Cuba' },
  CZ: { name: 'Czech Republic' },
  EG: { name: 'Egypt' },
  SV: { name: 'Salvador' },
  FR: { name: 'France' },
  GE: { name: 'Georgia' },
  DE: { name: 'Germany' },
  GR: { name: 'Greece' },
  HK: { name: 'HongKong' },
  HU: { name: 'Hungary' },
  IN: { name: 'India' },
  ID: { name: 'Indonesia' },
  IE: { name: 'Ireland' },
  IL: { name: 'Israel' },
  IT: { name: 'Italy' },
  JP: { name: 'Japan' },
  KR: { name: 'Korea' },
  LV: { name: 'Latvia' },
  LT: { name: 'Lithuania' },
  MY: { name: 'Malaysia' },
  MX: { name: 'Mexico' },
  MA: { name: 'Morocco' },
  NL: { name: 'Netherlands' },
  NG: { name: 'Nigeria' },
  NO: { name: 'Norway' },
  PL: { name: 'Poland' },
  PT: { name: 'Portugal' },
  RO: { name: 'Romania' },
  RU: { name: 'Russian Federation' },
  SA: { name: 'Saudi Arabia' },
  RS: { name: 'Serbia' },
  SK: { name: 'Slovakia' },
  SI: { name: 'Slovenia' },
  ZA: { name: 'South Africa' },
  ES: { name: 'Spain' },
  SE: { name: 'Sweden' },
  CH: { name: 'Switzerland' },
  TW: { name: 'Taiwan' },
  TH: { name: 'Thailand' },
  TR: { name: 'Turkey' },
  UA: { name: 'Ukraine' },
  AE: { name: 'United Arab Emirates' },
  GB: { name: 'United Kingdom' },
  US: { name: 'United States' },
  VE: { name: 'Venezuela' }
};
